'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { compareBids } from '../../lib/procurement/engine';
import { demoState } from '../../lib/procurement/demo';
import type { AuditEvent, Bid, ProcurementProject, ProcurementState, Vendor } from '../../lib/procurement/types';

const STORAGE_KEY = 'p-procurement-governance-v1';
const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const cloneDemo = (): ProcurementState => JSON.parse(JSON.stringify(demoState));
const money = (value: number, currency = 'VND') => new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value);

function addEvent(state: ProcurementState, projectId: string, eventType: string, entityType: string, entityId: string, afterSnapshot: unknown, reason?: string, actorId = 'owner-admin', actorRole = 'Owner Admin'): ProcurementState {
  const event: AuditEvent = { id: uid('audit'), projectId, actorId, actorRole, eventType, entityType, entityId, beforeSnapshot: null, afterSnapshot, reason, timestamp: new Date().toISOString() };
  return { ...state, audit: [...state.audit, event] };
}

export function ProcurementIndex() {
  const [state, setState] = useState<ProcurementState | null>(null);
  useEffect(() => { const saved = localStorage.getItem(STORAGE_KEY); setState(saved ? JSON.parse(saved) : cloneDemo()); }, []);
  useEffect(() => { if (state) localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [state]);
  if (!state) return <main><p>Loading workspace…</p></main>;
  return <main><div className="eyebrow">AI PROCUREMENT &amp; PROJECT GOVERNANCE</div><h1>Procurement workspace</h1><p>Make every project decision traceable, comparable, and reviewable.</p><div className="notice">AI may advise and summarize. Scoring and ranking are deterministic; authorized humans retain every award decision.</div><div className="toolbar"><h2>Projects</h2><a className="button" href="/procurement/projects/new">+ New project</a></div>{state.projects.map(project => <a className="panel project-card" href={`/procurement/projects/${project.id}`} key={project.id}><div className="summary"><b>{project.name}</b><span>{project.owner}</span><span>{project.location}</span><span className="badge">{project.status}</span></div><p>{project.package.name} · {project.package.quantity} {project.package.unit} · Budget {money(project.estimatedBudget, project.currency)}</p></a>)}</main>;
}

export function ProjectCreator() {
  const [error, setError] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const weights = { technical: Number(data.get('technicalWeight')), commercial: Number(data.get('commercialWeight')), delivery: Number(data.get('deliveryWeight')), compliance: Number(data.get('complianceWeight')) };
    if (Object.values(weights).reduce((a, b) => a + b, 0) !== 100) return setError('Scoring weights must total exactly 100%.');
    const projectId = uid('project'); const packageId = uid('package'); const now = new Date().toISOString();
    const project: ProcurementProject = { id: projectId, name: String(data.get('name')), owner: String(data.get('owner')), location: String(data.get('location')), currency: String(data.get('currency')), estimatedBudget: Number(data.get('budget')), procurementMethod: 'sealed_bid', bidOpenAt: String(data.get('openAt')), bidCloseAt: String(data.get('closeAt')), status: 'draft', createdBy: 'owner-admin', createdAt: now, package: { id: packageId, name: String(data.get('packageName')), description: String(data.get('description')), quantity: Number(data.get('quantity')), unit: String(data.get('unit')), technicalRequirements: String(data.get('requirements')), requiredDocuments: String(data.get('documents')).split(',').map(v => v.trim()).filter(Boolean), budgetMin: Number(data.get('budgetMin')), budgetMax: Number(data.get('budgetMax')), weights } };
    const saved = localStorage.getItem(STORAGE_KEY); let state: ProcurementState = saved ? JSON.parse(saved) : cloneDemo();
    state = { ...state, projects: [...state.projects, project] }; state = addEvent(state, projectId, 'project.created', 'project', projectId, project); state = addEvent(state, projectId, 'package.created', 'package', packageId, project.package);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); window.location.href = `/procurement/projects/${projectId}`;
  };
  return <main><div className="eyebrow">NEW PROCUREMENT PROJECT</div><h1>Project and package</h1><p>Configure one package and its approved scoring baseline.</p><form className="panel" onSubmit={submit}><div className="grid"><label>Project name<input name="name" required/></label><label>Client / owner<input name="owner" required/></label><label>Location<input name="location" required/></label><label>Currency<select name="currency" defaultValue="VND"><option>VND</option><option>USD</option><option>SGD</option></select></label><label>Estimated budget<input name="budget" type="number" min="0" required/></label><label>Package name<input name="packageName" required/></label><label>Bid opens<input name="openAt" type="datetime-local" required/></label><label>Bid closes<input name="closeAt" type="datetime-local" required/></label><label>Quantity<input name="quantity" type="number" min="1" required/></label><label>Unit<input name="unit" defaultValue="sets" required/></label><label>Package budget minimum<input name="budgetMin" type="number" min="0" required/></label><label>Package budget maximum<input name="budgetMax" type="number" min="0" required/></label><label className="full">Description<textarea name="description" required/></label><label className="full">Technical requirements<textarea name="requirements" required/></label><label className="full">Required documents (comma-separated)<input name="documents" required/></label><label>Technical weight %<input name="technicalWeight" type="number" defaultValue="35" min="0" max="100" required/></label><label>Commercial weight %<input name="commercialWeight" type="number" defaultValue="40" min="0" max="100" required/></label><label>Delivery weight %<input name="deliveryWeight" type="number" defaultValue="15" min="0" max="100" required/></label><label>Compliance weight %<input name="complianceWeight" type="number" defaultValue="10" min="0" max="100" required/></label></div>{error && <p className="error">{error}</p>}<div className="actions"><button type="submit">Create project</button><a className="button secondary" href="/procurement">Cancel</a></div></form></main>;
}

type Tab = 'overview' | 'vendors' | 'bids' | 'comparison' | 'audit';
export function ProjectWorkspace({ projectId, initialTab = 'overview' }: { projectId: string; initialTab?: Tab }) {
  const [state, setState] = useState<ProcurementState | null>(null); const [tab, setTab] = useState<Tab>(initialTab); const [error, setError] = useState('');
  useEffect(() => { const saved = localStorage.getItem(STORAGE_KEY); setState(saved ? JSON.parse(saved) : cloneDemo()); }, []);
  useEffect(() => { if (state) localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [state]);
  const project = state?.projects.find(item => item.id === projectId);
  const invitations = useMemo(() => state?.invitations.filter(item => item.projectId === projectId) ?? [], [state, projectId]);
  const bids = useMemo(() => state?.bids.filter(item => item.projectId === projectId) ?? [], [state, projectId]);
  if (!state) return <main><p>Loading project…</p></main>; if (!project) return <main><h1>Project not found</h1><a href="/procurement">Back to projects</a></main>;
  const update = (next: ProcurementState) => { setState(next); setError(''); };
  const inviteVendor = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const vendor: Vendor = { id: uid('vendor'), name: String(data.get('vendorName')), email: String(data.get('email')) }; const invitation = { id: uid('invite'), projectId, vendorId: vendor.id, invitedAt: new Date().toISOString(), status: 'invited' as const, invitationVersion: 1 }; let next = { ...state, vendors: [...state.vendors, vendor], invitations: [...state.invitations, invitation], projects: state.projects.map(item => item.id === projectId ? { ...item, status: 'inviting' as const } : item) }; next = addEvent(next, projectId, 'vendor.invited', 'invitation', invitation.id, { vendor, invitation }); update(next); event.currentTarget.reset(); };
  const accept = (id: string) => { const acceptedAt = new Date().toISOString(); let next = { ...state, invitations: state.invitations.map(item => item.id === id ? { ...item, status: 'accepted' as const, acceptedAt } : item), projects: state.projects.map(item => item.id === projectId ? { ...item, status: 'bidding' as const } : item) }; next = addEvent(next, projectId, 'invitation.accepted', 'invitation', id, { status: 'accepted', acceptedAt }, undefined, state.invitations.find(i => i.id === id)?.vendorId, 'Vendor'); update(next); };
  const submitBid = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const vendorId = String(data.get('vendorId')); if (bids.some(bid => bid.vendorId === vendorId)) return setError('This vendor already has a locked bid in round 1.'); if (project.status === 'closed') return setError('Bidding is closed. Locked bids cannot be edited.'); const nowMs = Date.now(); if (nowMs < new Date(project.bidOpenAt).getTime()) return setError('The configured bid window has not opened.'); if (nowMs > new Date(project.bidCloseAt).getTime()) return setError('The configured bid deadline has passed. Close the round or formally open a revision round.'); const now = new Date(nowMs).toISOString(); const bid: Bid = { id: uid('bid'), projectId, packageId: project.package.id, vendorId, round: 1, submittedAt: now, currency: project.currency, totalPrice: Number(data.get('price')), deliveryDays: Number(data.get('delivery')), paymentTerms: String(data.get('terms')), warrantyMonths: Number(data.get('warranty')), technicalScore: Number(data.get('technical')), complianceScore: Number(data.get('compliance')), scopeExclusions: String(data.get('exclusions')), documentsComplete: data.get('documentsComplete') === 'on', status: 'locked', lockedAt: now }; let next = { ...state, bids: [...state.bids, bid] }; next = addEvent(next, projectId, 'bid.submitted_and_locked', 'bid', bid.id, { vendorId, round: 1, submittedAt: now, status: 'locked', lockedAt: now }, undefined, vendorId, 'Vendor'); update(next); event.currentTarget.reset(); };
  const closeBidding = () => { if (bids.length < 3) return setError('At least three sealed bids are required for this demo slice.'); const now = new Date().toISOString(); let next = { ...state, projects: state.projects.map(item => item.id === projectId ? { ...item, status: 'closed' as const, bidCloseAt: now } : item) }; next = addEvent(next, projectId, 'bidding.closed', 'project', projectId, { status: 'closed', closedAt: now }); update(next); setTab('comparison'); };
  const comparison = project.status === 'closed' ? compareBids(bids, state.vendors, project.package) : [];
  const override = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const vendorId = String(data.get('vendorId')); const reason = String(data.get('reason')).trim(); if (!reason) return setError('A written reason is required for every override.'); let next = { ...state, awardOverrides: { ...state.awardOverrides, [projectId]: { vendorId, reason, createdAt: new Date().toISOString() } } }; next = addEvent(next, projectId, 'recommendation.overridden', 'comparison', projectId, { deterministicRankOne: comparison[0]?.vendorId, selectedVendor: vendorId }, reason); update(next); };
  return <main><a href="/procurement">← All projects</a><div className="toolbar"><div><div className="eyebrow">SEALED BID · ROUND 1</div><h1>{project.name}</h1><div className="summary"><span><b>Owner:</b> {project.owner}</span><span><b>Package:</b> {project.package.name}</span><span className="badge">{project.status}</span></div></div>{project.status !== 'closed' && <button onClick={closeBidding}>Close bidding</button>}</div><div className="notice">Bids remain sealed from buyer comparison until bidding is closed. Submission locks the bid immediately. Humans decide any award.</div>{error && <p className="error">{error}</p>}<div className="tabs">{(['overview','vendors','bids','comparison','audit'] as Tab[]).map(name => <button className={tab === name ? 'active' : ''} onClick={() => setTab(name)} key={name}>{name[0].toUpperCase()+name.slice(1)}</button>)}</div>
  {tab === 'overview' && <Overview project={project} invitations={invitations.length} bids={bids.length}/>} {tab === 'vendors' && <Vendors state={state} invitations={invitations} inviteVendor={inviteVendor} accept={accept}/>} {tab === 'bids' && <Bids project={project} state={state} invitations={invitations} bids={bids} submitBid={submitBid}/>} {tab === 'comparison' && <Comparison project={project} state={state} rows={comparison} override={override}/>} {tab === 'audit' && <Audit events={state.audit.filter(event => event.projectId === projectId)}/>}</main>;
}

function Overview({ project, invitations, bids }: { project: ProcurementProject; invitations: number; bids: number }) { const total = Object.values(project.package.weights).reduce((a,b)=>a+b,0); return <><div className="metrics"><div className="metric"><b>{invitations}</b><span>Invited vendors</span></div><div className="metric"><b>{bids}</b><span>Locked bids</span></div><div className="metric"><b>{total}%</b><span>Validated weights</span></div><div className="metric"><b>{money(project.estimatedBudget,project.currency)}</b><span>Estimated budget</span></div></div><section className="panel"><h2>{project.package.name}</h2><p>{project.package.description}</p><div className="summary"><span><b>Scope:</b> {project.package.quantity} {project.package.unit}</span><span><b>Technical:</b> {project.package.weights.technical}%</span><span><b>Commercial:</b> {project.package.weights.commercial}%</span><span><b>Delivery:</b> {project.package.weights.delivery}%</span><span><b>Compliance:</b> {project.package.weights.compliance}%</span></div></section></>; }
function Vendors({ state, invitations, inviteVendor, accept }: { state: ProcurementState; invitations: ProcurementState['invitations']; inviteVendor: (e: FormEvent<HTMLFormElement>)=>void; accept:(id:string)=>void }) { return <><form className="panel" onSubmit={inviteVendor}><h2>Invite vendor</h2><div className="grid"><label>Vendor name<input name="vendorName" required/></label><label>Email<input name="email" type="email" required/></label></div><div className="actions"><button>Send mock invitation</button></div></form><div className="panel table-wrap"><table><thead><tr><th>Vendor</th><th>Email</th><th>Version</th><th>Status</th><th>Action</th></tr></thead><tbody>{invitations.map(invite=>{const vendor=state.vendors.find(v=>v.id===invite.vendorId);return <tr key={invite.id}><td>{vendor?.name}</td><td>{vendor?.email}</td><td>v{invite.invitationVersion}</td><td><span className="badge">{invite.status}</span></td><td>{invite.status==='invited'&&<button onClick={()=>accept(invite.id)}>Accept as vendor</button>}</td></tr>})}</tbody></table></div></>; }
function Bids({ project, state, invitations, bids, submitBid }: { project:ProcurementProject; state:ProcurementState; invitations:ProcurementState['invitations']; bids:Bid[]; submitBid:(e:FormEvent<HTMLFormElement>)=>void }) { const eligible=invitations.filter(i=>i.status==='accepted'&&!bids.some(b=>b.vendorId===i.vendorId)); return <><form className="panel" onSubmit={submitBid}><h2>Vendor bid submission</h2><p>Submitting seals and locks the bid. A locked bid has no edit action.</p><div className="grid"><label>Vendor<select name="vendorId" required><option value="">Select accepted vendor</option>{eligible.map(i=><option value={i.vendorId} key={i.id}>{state.vendors.find(v=>v.id===i.vendorId)?.name}</option>)}</select></label><label>Total price ({project.currency})<input name="price" type="number" min="1" required/></label><label>Delivery days<input name="delivery" type="number" min="1" required/></label><label>Payment terms<input name="terms" placeholder="50/50" required/></label><label>Warranty months<input name="warranty" type="number" min="0" required/></label><label>Technical score (0–100)<input name="technical" type="number" min="0" max="100" required/></label><label>Compliance score (0–100)<input name="compliance" type="number" min="0" max="100" required/></label><label>Scope exclusions<input name="exclusions"/></label><label className="full"><span><input name="documentsComplete" type="checkbox"/> Required documents complete</span></label></div><div className="actions"><button disabled={!eligible.length||project.status==='closed'}>Submit and lock bid</button></div></form><div className="panel table-wrap"><table><thead><tr><th>Vendor</th><th>Submission</th><th>Commercial data</th><th>Status</th></tr></thead><tbody>{bids.map(bid=><tr key={bid.id}><td>{state.vendors.find(v=>v.id===bid.vendorId)?.name}</td><td>{new Date(bid.submittedAt).toLocaleString()}</td><td>{project.status==='closed'?money(bid.totalPrice,bid.currency):<span className="sealed">Sealed until close</span>}</td><td><span className="badge locked">Locked</span></td></tr>)}</tbody></table></div></>; }
function Comparison({ project, state, rows, override }: { project:ProcurementProject; state:ProcurementState; rows:ReturnType<typeof compareBids>; override:(e:FormEvent<HTMLFormElement>)=>void }) { if(project.status!=='closed')return <div className="panel empty">Comparison stays unavailable until bidding is formally closed.</div>; const selected=state.awardOverrides[project.id]; return <><div className="panel table-wrap"><h2>Deterministic comparison</h2><table><thead><tr><th>Rank</th><th>Vendor</th><th>Price</th><th>Normalized</th><th>Technical</th><th>Commercial</th><th>Delivery</th><th>Compliance</th><th>Total</th><th>Review flags</th></tr></thead><tbody>{rows.map(row=><tr key={row.vendorId}><td className="rank">#{row.rank}</td><td>{row.vendorName}</td><td>{money(row.totalPrice,project.currency)}</td><td>{row.normalizedPrice}</td><td>{row.technicalScore}</td><td>{row.commercialScore}</td><td>{row.deliveryScore}</td><td>{row.complianceScore}</td><td><b>{row.totalWeightedScore}</b></td><td>{row.flags.map(flag=><div className="flag" key={flag}>⚑ {flag}</div>)}</td></tr>)}</tbody></table><p className="score-note">Commercial = lowest price ÷ submitted price × 100. Delivery = fastest delivery ÷ submitted delivery × 100. Total applies the approved package weights. Ties resolve by lower price, then vendor name.</p></div><form className="panel" onSubmit={override}><h2>Human award direction</h2><p>The ranking is advice from deterministic rules. An authorized human may select another vendor only with a recorded reason.</p><div className="grid"><label>Selected vendor<select name="vendorId" defaultValue={selected?.vendorId??rows[0]?.vendorId}>{rows.map(row=><option value={row.vendorId} key={row.vendorId}>{row.vendorName} (rank #{row.rank})</option>)}</select></label><label>Override reason<textarea name="reason" defaultValue={selected?.reason} placeholder="Required for a recorded human selection"/></label></div><button>Record human decision</button>{selected&&<p>Recorded selection: <b>{state.vendors.find(v=>v.id===selected.vendorId)?.name}</b> — {selected.reason}</p>}</form></>; }
function Audit({ events }: { events: AuditEvent[] }) { return <section className="panel"><h2>Append-only audit timeline</h2><p>New events are appended; sensitive history is never silently replaced.</p><ol className="timeline">{[...events].reverse().map(event=><li key={event.id}><b>{event.eventType}</b><span>{event.actorRole} · {event.entityType} {event.entityId}</span>{event.reason&&<p>Reason: {event.reason}</p>}<small>{new Date(event.timestamp).toLocaleString()} · {event.id}</small></li>)}</ol></section>; }
